import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import { FaArrowRight, FaCheckCircle, FaSpinner, FaUtensils } from "react-icons/fa";
import { Link } from "react-router-dom";

const API_URL = "http://localhost:5000";
const labels = { calories: ["Calories", "kcal"], protein: ["Protein", "g"], carbs: ["Carbs", "g"], fat: ["Fat", "g"] };
const requestHeaders = () => ({ Authorization: `Bearer ${localStorage.getItem("token")}`, "X-Timezone": Intl.DateTimeFormat().resolvedOptions().timeZone });

export default function DailyAnalytics() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { const token = localStorage.getItem("token"); if (!token) { setError("Please log in to see daily progress."); setLoading(false); return; } try { setLoading(true); const response = await axios.get(`${API_URL}/api/food/analytics/today`, { headers: requestHeaders() }); setData(response.data); setError(""); } catch (e) { setError(e.response?.data?.message || "Failed to load today's guide."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); const onScan = () => load(); window.addEventListener("food-scan-created", onScan); const channel = "BroadcastChannel" in window ? new BroadcastChannel("diet-app") : null; if (channel) channel.onmessage = onScan; const refresh = window.setInterval(load, 60_000); return () => { window.removeEventListener("food-scan-created", onScan); channel?.close(); window.clearInterval(refresh); }; }, [load]);
  if (loading && !data) return <State message="Loading today's progress..." spinner />;
  if (error) return <State message={error} action="Set up profile" />;
  const hasScans = data.itemsToday > 0;
  return <main className="min-h-screen bg-slate-50 pt-24 pb-12 px-4"><div className="max-w-5xl mx-auto"><section className="rounded-3xl bg-gradient-to-br from-green-800 to-emerald-600 p-7 md:p-9 text-white shadow-lg"><div className="flex flex-col md:flex-row md:justify-between gap-5"><div><p className="text-sm uppercase tracking-widest text-green-100 font-semibold">Daily goal · {data.date}</p><h1 className="text-3xl font-bold mt-2">Today's nutrition progress</h1><p className="mt-2 text-green-50">{hasScans ? `${data.itemsToday} scanned meal${data.itemsToday === 1 ? "" : "s"} included in your totals.` : "Start fresh today — your progress is at zero."}</p></div><Link to="/scan" className="self-start rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-green-800 hover:bg-green-50">Scan food</Link></div><div className="mt-6 rounded-2xl bg-white/15 p-4 text-sm font-medium">{data.insights[0]}</div></section>
    {hasScans ? <><section className="grid md:grid-cols-2 gap-4 mt-6">{data.nutrients.map((item) => <NutrientCard key={item.key} item={item} />)}</section><section className="mt-6 rounded-3xl bg-white p-6 shadow-sm border border-slate-100"><h2 className="font-bold text-xl text-slate-800">Today's scanned foods</h2><div className="mt-4 grid md:grid-cols-2 gap-3">{data.scans.map((scan) => <div key={scan._id} className="rounded-2xl bg-slate-50 p-4 flex justify-between gap-3"><div><p className="font-semibold text-slate-800">{scan.foodName}</p><p className="mt-1 text-xs text-slate-500">Protein {scan.protein}g · Carbs {scan.carbs}g · Fat {scan.fat}g</p></div><p className="font-bold text-slate-700 whitespace-nowrap">{scan.calories} kcal</p></div>)}</div></section></> : <EmptyToday />}
    <section className="mt-6 grid md:grid-cols-[1fr_auto] gap-4 items-center bg-slate-800 text-white rounded-2xl p-6"><div><h2 className="font-bold text-xl">Next best step</h2><p className="text-slate-300 mt-1">{data.insights[1]}</p></div><Link to="/week" className="rounded-xl bg-green-500 hover:bg-green-400 px-5 py-3 font-semibold whitespace-nowrap">Weekly menu <FaArrowRight className="inline ml-1" /></Link></section>
  </div></main>;
}
function NutrientCard({ item }) { const [label, unit] = labels[item.key]; const width = Math.min(100, item.percentage); return <article className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100"><div className="flex justify-between gap-3"><h2 className="font-bold text-slate-800">{label}</h2><span className={item.status === "over" ? "text-red-600 text-sm font-semibold" : "text-green-700 text-sm font-semibold"}>{item.status === "over" ? `${item.overBy} ${unit} over` : `${item.remaining} ${unit} left`}</span></div><p className="mt-3 text-3xl font-bold text-slate-800">{item.consumed}<span className="text-sm font-medium text-slate-400"> / {item.target} {unit}</span></p><div className="h-2.5 rounded-full overflow-hidden bg-slate-100 mt-4"><div className={item.status === "over" ? "h-full bg-red-500" : "h-full bg-green-500"} style={{ width: `${width}%` }} /></div><p className="text-xs mt-2 text-slate-500">{item.percentage}% of daily target</p></article>; }
function EmptyToday() { return <section className="mt-6 rounded-3xl bg-white p-10 shadow-sm border border-slate-100 text-center"><FaUtensils className="mx-auto text-4xl text-green-600" /><h2 className="mt-4 text-xl font-bold text-slate-800">No food logged today</h2><p className="mt-2 text-slate-500">Yesterday's intake stays in your history. Scan your first meal to begin today's totals.</p><Link to="/scan" className="inline-block mt-5 rounded-xl bg-green-700 px-5 py-3 font-semibold text-white">Scan your first meal</Link></section>; }
function State({ message, spinner, action }) { return <main className="min-h-screen bg-slate-50 pt-28 px-4"><div className="max-w-md mx-auto rounded-3xl bg-white p-8 shadow-sm text-center text-slate-600">{spinner ? <FaSpinner className="mx-auto animate-spin text-2xl text-green-700" /> : <FaCheckCircle className="mx-auto text-2xl text-red-500" />}<p className="mt-3">{message}</p>{action && <Link to="/form" className="inline-block mt-4 text-green-700 font-semibold">{action}</Link>}</div></main>; }
