import { useEffect, useRef, useState } from "react";
import axios from "axios";
import Webcam from "react-webcam";
import { FaCamera, FaCheckCircle, FaImage, FaSpinner, FaUtensils } from "react-icons/fa";
import { Link } from "react-router-dom";

const API_URL = "http://localhost:5000";
const headers = () => ({ Authorization: `Bearer ${localStorage.getItem("token")}`, "X-Timezone": Intl.DateTimeFormat().resolvedOptions().timeZone });
const time = (value) => new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(value));

export default function Scan() {
  const webcam = useRef(null); const [scans, setScans] = useState([]); const [listLoading, setListLoading] = useState(true); const [error, setError] = useState("");
  const [camera, setCamera] = useState(false); const [image, setImage] = useState(null); const [preview, setPreview] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null); const token = localStorage.getItem("token");
  const loadToday = async () => { if (!token) return setListLoading(false); try { setListLoading(true); const { data } = await axios.get(`${API_URL}/api/food/history/today`, { headers: headers() }); setScans(data.scans); setError(""); } catch (e) { setError(e.response?.data?.message || "Could not load today's meals."); } finally { setListLoading(false); } };
  useEffect(() => { loadToday(); }, []);
  const pick = (event) => { const file = event.target.files?.[0]; if (!file) return; setImage(file); setPreview(URL.createObjectURL(file)); setResult(null); };
  const capture = () => { const shot = webcam.current?.getScreenshot(); if (shot) { setImage(shot); setPreview(shot); setCamera(false); setResult(null); } };
  const reset = () => { if (preview.startsWith("blob:")) URL.revokeObjectURL(preview); setImage(null); setPreview(""); setResult(null); setError(""); };
  const analyze = async () => { if (!image) return; try { setLoading(true); setError(""); const form = new FormData(); if (image instanceof File) form.append("image", image); else form.append("image", await (await fetch(image)).blob(), "capture.jpg"); const { data } = await axios.post(`${API_URL}/api/food/scan`, form, { headers: headers() }); setResult(data); setScans((current) => [data, ...current]); window.dispatchEvent(new Event("food-scan-created")); if ("BroadcastChannel" in window) new BroadcastChannel("diet-app").postMessage("food-scan-created"); } catch (e) { setError(e.response?.data?.message || "The food image could not be analyzed. Please try another photo."); } finally { setLoading(false); } };
  if (!token) return <EmptyLogin />;
  return <main className="min-h-screen bg-slate-50 pt-24 pb-12 px-4"><div className="max-w-6xl mx-auto"><header className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 mb-7"><div><p className="text-sm font-semibold uppercase tracking-widest text-green-700">Food scanner</p><h1 className="text-3xl font-bold text-slate-800 mt-1">Track today's meals</h1><p className="text-slate-500 mt-1">Each scan is added to your daily goal immediately.</p></div><Link to="/daily" className="rounded-xl border border-green-700 px-4 py-2.5 text-sm font-semibold text-green-800 hover:bg-green-50">View daily goal</Link></header>
    <div className="grid lg:grid-cols-[1.05fr_.95fr] gap-6"><section className="rounded-3xl bg-white p-6 shadow-sm border border-slate-100"><h2 className="font-bold text-xl text-slate-800">Add a food</h2>{!preview && !camera && <div className="mt-5 grid sm:grid-cols-2 gap-3"><button onClick={() => setCamera(true)} className="rounded-2xl bg-green-700 p-6 text-left text-white hover:bg-green-800"><FaCamera className="text-2xl" /><p className="font-bold mt-4">Use camera</p><p className="text-sm text-green-100 mt-1">Capture your meal</p></button><label className="cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-6 text-left hover:border-green-500 hover:bg-green-50"><FaImage className="text-2xl text-green-700" /><p className="font-bold text-slate-800 mt-4">Upload photo</p><p className="text-sm text-slate-500 mt-1">Choose from your device</p><input hidden type="file" accept="image/*" onChange={pick} /></label></div>}
      {camera && <div className="mt-5"><Webcam ref={webcam} screenshotFormat="image/jpeg" className="w-full rounded-2xl" videoConstraints={{ facingMode: "environment" }} /><div className="flex gap-3 mt-3"><button onClick={capture} className="rounded-xl bg-green-700 px-4 py-2.5 font-semibold text-white">Capture</button><button onClick={() => setCamera(false)} className="rounded-xl bg-slate-100 px-4 py-2.5 font-semibold text-slate-700">Cancel</button></div></div>}
      {preview && <div className="mt-5"><img src={preview} alt="Selected food" className="h-64 w-full rounded-2xl object-cover" /><div className="flex flex-wrap gap-3 mt-3"><button disabled={loading} onClick={analyze} className="rounded-xl bg-green-700 px-4 py-2.5 font-semibold text-white disabled:opacity-60">{loading ? <><FaSpinner className="inline animate-spin mr-2" />Analyzing</> : "Analyze and add"}</button><button onClick={reset} disabled={loading} className="rounded-xl bg-slate-100 px-4 py-2.5 font-semibold text-slate-700">Choose another</button></div></div>}
      {error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{result && <><p className="mt-4 rounded-xl bg-green-50 p-3 text-sm text-green-800"><FaCheckCircle className="inline mr-2" />{result.foodName} was added to today's intake.</p><Nutrition values={result} /></>}</section>
      <TodayScans scans={scans} loading={listLoading} error={error} retry={loadToday} /></div></div></main>;
}

function Nutrition({ values }) { return <div className="mt-4 grid grid-cols-4 gap-2 text-center">{[["Calories", values.calories, "kcal"], ["Protein", values.protein, "g"], ["Carbs", values.carbs, "g"], ["Fat", values.fat, "g"]].map(([label, value, unit]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="font-bold text-slate-800">{value}{unit}</p><p className="text-xs text-slate-500">{label}</p></div>)}</div>; }
function TodayScans({ scans, loading, error, retry }) { return <section className="rounded-3xl bg-white p-6 shadow-sm border border-slate-100"><div className="flex justify-between items-center"><div><h2 className="font-bold text-xl text-slate-800">Today's scans</h2><p className="text-sm text-slate-500">Only meals from your local calendar day.</p></div><span className="rounded-full bg-green-50 px-3 py-1 text-sm font-semibold text-green-800">{scans.length} {scans.length === 1 ? "meal" : "meals"}</span></div>{loading ? <p className="py-12 text-center text-slate-500"><FaSpinner className="inline animate-spin mr-2" />Loading meals...</p> : error && !scans.length ? <div className="py-10 text-center text-red-700"><p>{error}</p><button onClick={retry} className="mt-3 text-sm font-semibold underline">Try again</button></div> : scans.length === 0 ? <div className="py-12 text-center"><FaUtensils className="mx-auto text-3xl text-slate-300" /><p className="mt-3 font-semibold text-slate-700">No meals scanned today</p><p className="mt-1 text-sm text-slate-500">Your daily progress starts at zero until you add food.</p></div> : <ul className="mt-4 divide-y divide-slate-100">{scans.map((scan) => <li key={scan._id} className="py-3 flex justify-between gap-4"><div><p className="font-semibold text-slate-800">{scan.foodName}</p><p className="text-xs text-slate-500">{time(scan.createdAt)} · P {scan.protein}g · C {scan.carbs}g · F {scan.fat}g</p></div><p className="font-bold text-slate-700 whitespace-nowrap">{scan.calories} kcal</p></li>)}</ul>}</section>; }
function EmptyLogin() { return <main className="min-h-screen bg-slate-50 pt-28 px-4"><div className="max-w-md mx-auto rounded-3xl bg-white p-8 shadow-sm border border-slate-100 text-center"><FaUtensils className="mx-auto text-3xl text-green-600" /><h1 className="mt-4 text-2xl font-bold text-slate-800">Scan your meals</h1><p className="mt-2 text-slate-500">Log in to scan food and track daily nutrition.</p><Link to="/login" className="inline-block mt-5 rounded-xl bg-green-700 px-5 py-3 font-semibold text-white">Log in</Link></div></main>; }
